api:
  insecure: true
  dashboard: true
log:
  level: debug
providers:
  docker:
    watch: true
    exposedByDefault: false
    network: traefik
  file:
    filename: /dynconf/dynconf.yml
    watch: true
entryPoints:
  web:
    address: :80
  websecure:
    address: :443
experimental:
  plugins:
    keycloakopenid:
      moduleName: "github.com/Gwojda/keycloakopenid"
      version: "v0.1.34"